#!/usr/bin/with-contenv bash

CONFIG_PATH=/data/options.json
SYSTEM_USER=/data/system_user.json

ENABLE_REGISTRATIONS=$(jq --raw-output ".logins | length" $CONFIG_PATH)
MYSQL_HOST=$(jq --raw-output ".MYSQL_HOST" $CONFIG_PATH)
MYSQL_USERNAME=$(jq --raw-output ".MYSQL_USERNAME" $CONFIG_PATH)
MYSQL_PASSWORD=$(jq --raw-output ".MYSQL_PASSWORD" $CONFIG_PATH)
LOGGING=$(bashio::info 'hassio.info.logging' '.logging')

echo "------------------"
echo "Starting Clarkson."
echo "------------------"

RUN_CMD="\
	MYSQL_HOST=${MYSQL_HOST} MYSQL_USERNAME=${MYSQL_USERNAME} \
	MYSQL_PASSWORD=${MYSQL_PASSWORD} ENABLE_REGISTRATIONS=${ENABLE_REGISTRATIONS:-false} \
	node clarkson.js"

cd /app/clarkson || exit

exec \
	s6-setuidgid abc /bin/bash -c "${RUN_CMD}"
